#!/bin/python

import argparse as ap
import numpy as np

def main():
	# Read in the arguments from every file in regular expression
	# create a dictionary of the necessary values
	# generate an output table
	# plot results 

if __name__ == '__main__':
	try:
		print("starting")
		main()
	except KeybordInterrupt:
		pass
